import React, { useEffect, useLayoutEffect, useRef, useState } from "react";
import { ArrowLeft, FileText, ShieldCheck, Cookie } from "lucide-react";
import gsap from "gsap";
import { ScrollTrigger } from "gsap/ScrollTrigger";
import Lenis from "@studio-freight/lenis";
import { PERF_LITE } from "../../utils/perf";

gsap.registerPlugin(ScrollTrigger);

const EFFECTIVE = "6 July 2026";
const COMPANY = "Scalera Studio";
const EMAIL = "contact.scalerastudio@gmail.com";

const DOCS = [
  {
    id: "terms",
    title: "Terms of Service",
    icon: FileText,
    intro: `These Terms of Service ("Terms") govern your access to and use of the ${COMPANY} website and the design, development, and related services we provide. By engaging our services or using this site, you agree to these Terms.`,
    sections: [
      {
        h: "1. Services",
        p: [
          `${COMPANY} provides custom website design, front-end and full-stack development, brand and interface design, SEO foundations, performance optimization, and related digital services. The specific scope, deliverables, timeline, and fees for any project are agreed in a separate proposal or written brief that, together with these Terms, forms our agreement.`,
        ],
      },
      {
        h: "2. Engagement & Deliverables",
        p: [
          "Work begins once a project brief is confirmed and any required deposit is received. Deliverables, milestones, and the number of included revision rounds are defined per project. Requests outside the agreed scope may be quoted separately as additional work.",
        ],
      },
      {
        h: "3. Fees & Payments",
        p: [
          "Fees are stated in the agreed proposal. Unless otherwise specified, an upfront deposit is required to reserve capacity and commence work, with the balance due at agreed milestones or before final delivery/deployment.",
          "Estimates generated by our on-site cost estimator are indicative ranges for guidance only and do not constitute a binding quote. Late payments may pause active work until the account is settled.",
        ],
      },
      {
        h: "4. Revisions & Timelines",
        p: [
          "Project timelines assume timely feedback, content, and approvals from the client. Delays in providing materials or sign-off may shift delivery dates. Revisions beyond the included rounds are billed at our standard rate.",
        ],
      },
      {
        h: "5. Intellectual Property",
        p: [
          "Upon full payment, ownership of the final, delivered project assets created specifically for you transfers to you, excluding any third-party assets, open-source components, fonts, or licensed materials, which remain governed by their respective licenses.",
          `${COMPANY} retains the right to display completed work in our portfolio and marketing unless a written confidentiality arrangement states otherwise.`,
        ],
      },
      {
        h: "6. Client Responsibilities",
        p: [
          "You are responsible for providing accurate information, timely content, and lawful materials, and for ensuring you hold the rights to any content you supply. You agree not to use our services for any unlawful, infringing, or harmful purpose.",
        ],
      },
      {
        h: "7. Third-Party Services",
        p: [
          "Projects may rely on third-party platforms (e.g. hosting, domains, analytics, payment providers). Your use of those services is subject to their own terms, and we are not responsible for their availability, pricing, or policies.",
        ],
      },
      {
        h: "8. Warranties & Limitation of Liability",
        p: [
          `Services are provided with reasonable skill and care but on an "as is" basis without further warranties. To the maximum extent permitted by law, ${COMPANY} is not liable for indirect, incidental, or consequential damages, and our total liability for any claim is limited to the fees paid for the specific work giving rise to the claim.`,
        ],
      },
      {
        h: "9. Termination",
        p: [
          "Either party may terminate an engagement with written notice. On termination, you agree to pay for all work completed up to the termination date. Deposits are non-refundable once work has commenced, except as required by law.",
        ],
      },
      {
        h: "10. Governing Law",
        p: [
          "These Terms are governed by the laws of India, and any disputes are subject to the exclusive jurisdiction of the competent courts in India.",
        ],
      },
      {
        h: "11. Changes to These Terms",
        p: [
          "We may update these Terms from time to time. The latest version will always be available on this page with its effective date. Continued use of our services after changes take effect constitutes acceptance.",
        ],
      },
    ],
  },
  {
    id: "privacy",
    title: "Privacy Policy",
    icon: ShieldCheck,
    intro: `This Privacy Policy explains how ${COMPANY} collects, uses, and protects your information when you visit our website or engage our services. We are committed to handling your data responsibly and transparently.`,
    sections: [
      {
        h: "1. Information We Collect",
        p: ["We collect information you provide directly and a limited amount of technical data automatically."],
        list: [
          "Contact details you submit through our forms — such as your name, email, phone/WhatsApp number, and project details.",
          "Communication content when you email or message us.",
          "Technical data such as browser type, device, approximate location, and pages visited, collected via cookies and analytics.",
        ],
      },
      {
        h: "2. How We Use Your Information",
        p: ["We use the information we collect to:"],
        list: [
          "Respond to enquiries and prepare project proposals and estimates.",
          "Deliver, maintain, and improve our services.",
          "Communicate with you about your project or account.",
          "Understand site usage and improve performance and content.",
          "Comply with legal obligations and protect our rights.",
        ],
      },
      {
        h: "3. Legal Basis",
        p: [
          "We process personal data where you have given consent, where processing is necessary to perform a contract with you, or where we have a legitimate interest in operating and improving our business, in each case as permitted by applicable law.",
        ],
      },
      {
        h: "4. Cookies & Analytics",
        p: [
          "We use cookies and similar technologies to run the site and understand how it is used. See our Cookie Policy below for details and how to manage your preferences.",
        ],
      },
      {
        h: "5. Sharing Your Information",
        p: [
          "We do not sell your personal information. We may share it with trusted service providers who help us operate (for example, form/email handling, hosting, and analytics), and where required by law. These providers are only permitted to use your data to perform services on our behalf.",
        ],
      },
      {
        h: "6. Data Retention & Security",
        p: [
          "We keep personal data only for as long as necessary for the purposes described here or as required by law, then delete or anonymize it. We apply reasonable technical and organizational measures to protect your data, though no method of transmission over the internet is fully secure.",
        ],
      },
      {
        h: "7. Your Rights",
        p: [
          `Subject to applicable law, you may request access to, correction of, or deletion of your personal data, and you may object to or withdraw consent for certain processing. To exercise these rights, contact us at ${EMAIL}.`,
        ],
      },
      {
        h: "8. Third-Party Links",
        p: [
          "Our site may link to external websites. We are not responsible for the privacy practices or content of those sites and encourage you to review their policies.",
        ],
      },
      {
        h: "9. Children's Privacy",
        p: [
          "Our services are intended for businesses and adults. We do not knowingly collect personal data from children.",
        ],
      },
      {
        h: "10. Changes to This Policy",
        p: [
          "We may update this Privacy Policy periodically. The current version and its effective date will always be shown on this page.",
        ],
      },
    ],
  },
  {
    id: "cookies",
    title: "Cookie Policy",
    icon: Cookie,
    intro: `This Cookie Policy explains what cookies are and how ${COMPANY} uses them on this website.`,
    sections: [
      {
        h: "1. What Are Cookies",
        p: [
          "Cookies are small text files placed on your device when you visit a website. They help the site function, remember preferences, and understand how it is used.",
        ],
      },
      {
        h: "2. How We Use Cookies",
        p: ["We use a limited set of cookies and similar technologies for the following purposes:"],
        list: [
          "Essential — required for the site to function and load correctly.",
          "Preferences — remember choices such as device/performance settings.",
          "Analytics — help us understand aggregate usage so we can improve the experience.",
        ],
      },
      {
        h: "3. Managing Cookies",
        p: [
          "Most browsers let you view, manage, block, or delete cookies through their settings. Disabling certain cookies may affect how parts of the site work. You can also often opt out of analytics tracking via your browser or device controls.",
        ],
      },
      {
        h: "4. Changes",
        p: [
          "We may update this Cookie Policy as our practices evolve. The latest version will always be available on this page.",
        ],
      },
    ],
  },
];

const Legal = () => {
  const [active, setActive] = useState(DOCS[0].id);
  const lenisRef = useRef(null);
  const rootRef = useRef(null);

  // Smooth scrolling + load & scroll-reveal animations
  useLayoutEffect(() => {
    let lenis = null;
    let tick = null;

    if (!PERF_LITE) {
      lenis = new Lenis({
        duration: 1.2,
        easing: (t) => Math.min(1, 1.001 - Math.pow(2, -10 * t)),
        smoothTouch: false,
      });
      lenisRef.current = lenis;
      lenis.on("scroll", ScrollTrigger.update);
      tick = (time) => lenis.raf(time * 1000);
      gsap.ticker.add(tick);
      gsap.ticker.lagSmoothing(0);
    }

    const ctx = gsap.context(() => {
      if (PERF_LITE) return; // low-end: keep everything visible, no motion

      // Entrance / load animation
      const tl = gsap.timeline({ defaults: { ease: "expo.out" } });
      tl.from(".legal-header", { y: -40, opacity: 0, duration: 0.9 })
        .from(".legal-hero .section-label", { opacity: 0, y: 18, duration: 0.7 }, "-=0.5")
        .from(".legal-hero h1", { opacity: 0, y: 34, duration: 1 }, "-=0.4")
        .from(".legal-hero-sub", { opacity: 0, y: 22, duration: 0.9 }, "-=0.7")
        .from(".legal-toc-inner", { opacity: 0, y: 26, duration: 0.9 }, "-=0.6")
        .from(
          ".legal-doc:first-of-type .legal-doc-head, .legal-doc:first-of-type .legal-updated, .legal-doc:first-of-type .legal-intro",
          { opacity: 0, y: 22, duration: 0.8, stagger: 0.08 },
          "-=0.6",
        );

      // Scroll reveals for each document section + the contact card
      gsap.utils.toArray(".legal-doc").forEach((doc, i) => {
        if (i === 0) return; // first doc handled by the load timeline
        gsap.from(doc, {
          opacity: 0,
          y: 48,
          duration: 1.1,
          ease: "expo.out",
          scrollTrigger: { trigger: doc, start: "top 85%" },
        });
      });
      gsap.from(".legal-contact", {
        opacity: 0,
        y: 40,
        scale: 0.98,
        duration: 1,
        ease: "expo.out",
        scrollTrigger: { trigger: ".legal-contact", start: "top 88%" },
      });
    }, rootRef);

    // Honour an incoming hash (e.g. arriving from footer → /legal.html#privacy)
    if (window.location.hash) {
      const el = document.querySelector(window.location.hash);
      if (el) {
        requestAnimationFrame(() => {
          if (lenis) lenis.scrollTo(el, { offset: -80, immediate: false });
          else el.scrollIntoView();
        });
      }
    }

    return () => {
      ctx.revert();
      if (lenis) {
        lenis.destroy();
        if (tick) gsap.ticker.remove(tick);
        lenisRef.current = null;
      }
    };
  }, []);

  const handleTocClick = (id) => (e) => {
    e.preventDefault();
    const el = document.getElementById(id);
    if (!el) return;
    if (lenisRef.current) {
      lenisRef.current.scrollTo(el, {
        offset: -80,
        duration: 1.3,
        easing: (t) => 1 - Math.pow(1 - t, 4),
      });
    } else {
      el.scrollIntoView({ behavior: "smooth" });
    }
  };

  // Scroll-spy: highlight the current document in the table of contents
  useEffect(() => {
    const observer = new IntersectionObserver(
      (entries) => {
        entries.forEach((entry) => {
          if (entry.isIntersecting) setActive(entry.target.id);
        });
      },
      { rootMargin: "-45% 0px -50% 0px", threshold: 0 },
    );
    DOCS.forEach((d) => {
      const el = document.getElementById(d.id);
      if (el) observer.observe(el);
    });
    return () => observer.disconnect();
  }, []);

  return (
    <div className="legal-page" ref={rootRef}>
      {/* Ambient atmosphere */}
      <div className="legal-bg" aria-hidden="true">
        <div className="legal-blob a" />
        <div className="legal-blob b" />
      </div>

      {/* Top bar */}
      <header className="legal-header">
        <a href="/" className="legal-logo">
          Scalera<span>.</span>
        </a>
        <a href="/" className="legal-back">
          <ArrowLeft size={15} strokeWidth={2} /> Back to Home
        </a>
      </header>

      <div className="legal-inner">
        {/* Hero */}
        <div className="legal-hero">
          <div className="section-label">
            <span className="section-label-dot" /> Legal
          </div>
          <h1>Terms &amp; Policies</h1>
          <p className="legal-hero-sub">
            The agreements that govern working with {COMPANY} and how we handle
            your information. Effective {EFFECTIVE}.
          </p>
        </div>

        <div className="legal-layout">
          {/* Table of contents */}
          <aside className="legal-toc">
            <div className="legal-toc-inner">
              <span className="legal-toc-title">On this page</span>
              {DOCS.map((d) => {
                const Icon = d.icon;
                return (
                  <a
                    key={d.id}
                    href={`#${d.id}`}
                    onClick={handleTocClick(d.id)}
                    className={`legal-toc-link${active === d.id ? " is-active" : ""}`}
                  >
                    <Icon size={15} strokeWidth={1.7} />
                    {d.title}
                  </a>
                );
              })}
            </div>
          </aside>

          {/* Documents */}
          <main className="legal-content">
            {DOCS.map((d) => {
              const Icon = d.icon;
              return (
                <article key={d.id} id={d.id} className="legal-doc">
                  <div className="legal-doc-head">
                    <span className="legal-doc-icon">
                      <Icon size={20} strokeWidth={1.7} />
                    </span>
                    <h2>{d.title}</h2>
                  </div>
                  <p className="legal-updated">Last updated {EFFECTIVE}</p>
                  <p className="legal-intro">{d.intro}</p>

                  {d.sections.map((s, i) => (
                    <section key={i} className="legal-section">
                      <h3>{s.h}</h3>
                      {s.p?.map((para, j) => (
                        <p key={j}>{para}</p>
                      ))}
                      {s.list && (
                        <ul>
                          {s.list.map((li, k) => (
                            <li key={k}>{li}</li>
                          ))}
                        </ul>
                      )}
                    </section>
                  ))}
                </article>
              );
            })}

            {/* Contact card */}
            <div className="legal-contact">
              <h3>Questions?</h3>
              <p>
                If you have any questions about these terms or policies, reach out
                and we'll be glad to help.
              </p>
              <a href={`mailto:${EMAIL}`} className="legal-contact-btn">
                {EMAIL}
              </a>
            </div>
          </main>
        </div>
      </div>

      <footer className="legal-page-footer">
        <span>
          © {new Date().getFullYear()} {COMPANY} — All rights reserved.
        </span>
        <a href="/">Return to scalera.studio</a>
      </footer>
    </div>
  );
};

export default Legal;
